### ISSUE TITLE
Cant find MySQL Table?

### ISSUE THREAD

**Issue by FiberSprite** [jamiesage123/Project-HoneyPot-for-MyBB#1]
So i just installed the plugin and went to the logs and it cant find the table? https://i.gyazo.com/c0595d700f6ace91e0b48f4a5418e37c.png

**Comment by jamiesage123** [comment]
Hey FiberSprite,

Thanks for the report.

I have just tested on a clean copy of mybb (version 1.8.12) and the install process created the table as expected and I receive no errors when viewing the logs page.

If possible, can I get the version of mybb you're running, any relevant information about your server that you can provide (such as mysql version) and any other plugins on your mybb that you may think could conflict with this one.

I appreciate you taking your time to report this.

Jamie

**Comment by mustaphaturk** [comment]
Hi,
thanks for this plugin for mybb. I installed and activated honeypot for mybb without any problem (and i have bl key) but when i go to Tools & Maintenance/system logs/project honeypot it says:

Warning [2] require(/home/master/sitename.com/xxx/modules/tools/honeypot.php): failed to open stream: No such file or directory - Line: 766 - File: xxx/index.php PHP 5.6.31 (Linux)

file| line | function
/xxx/index.php | 766 | errorHandler->error

/xxx/index.php | 766 | require

Fatal error: require(): Failed opening required '/home/master/sitename.com/xxx/modules/tools/honeypot.php' (include_path='.:/usr/local/lib/php:/usr/local/php5/lib/pear') in /home/master/sitename.com/xxx/index.php on line 766

so what is that and what can i do for this errors?

**Comment by jamiesage123** [comment]
Hey @mustaphaturk,

Can you check that this file exists in your MyBB installation:

`/modules/tools/honeypot.php`

If it doesn't exist, you will have to copy the "admin" folder from this repository to your MyBB installation directory to create the necessary files.

If that doesn't fix your problem, please can you create a new issue so that I can have a look into it for you?

I am going to close this issue as the OP hasn't responded.

Cheers,

Jamie

**Comment by mustaphaturk** [comment]
do you mean

sitename.com/admin/modules/tools/honeypot.php ? Yes i have and it is this:

<?php
// Disallow direct access to this file for security reasons
if (!defined("IN_MYBB")) {
    die("Direct initialization of this file is not allowed.<br /><br />Please make sure IN_MYBB is defined.");
}

$page->add_breadcrumb_item($lang->honeypot, "index.php?module=tools-honeypot");

$sub_tabs['honeypot'] = array(
    'title' => $lang->honeypot,
    'link' => "index.php?module=tools-honeypot",
    'description' => $lang->honeypot_logs_desc
);

if (!$mybb->input['action']) {
    $page->output_header($lang->spam_logs);

    $page->output_nav_tabs($sub_tabs, 'honeypot');

    $perpage = $mybb->get_input('perpage', MyBB::INPUT_INT);
    if (!$perpage) {
        $perpage = 20;
    }

    $query = $db->simple_select("project_honeypot", "COUNT(id) AS count");
    $rescount = $db->fetch_field($query, "count");

    // Figure out if we need to display multiple pages.
    if ($mybb->input['page'] != "last") {
        $pagecnt = $mybb->get_input('page', MyBB::INPUT_INT);
    }

    $logcount = (int)$rescount;
    $pages = $logcount / $perpage;
    $pages = ceil($pages);

    if ($mybb->input['page'] == "last") {
        $pagecnt = $pages;
    }

    if ($pagecnt > $pages) {
        $pagecnt = 1;
    }

    if ($pagecnt) {
        $start = ($pagecnt - 1) * $perpage;
    } else {
        $start = 0;
        $pagecnt = 1;
    }

    $table = new Table;
    $table->construct_header($lang->honeypot_username, ['width' => '14.14%']);
    $table->construct_header($lang->honeypot_email, ['width' => '14.14%']);
    $table->construct_header($lang->honeypot_last_activity, ['width' => '14.14%']);
    $table->construct_header($lang->honeypot_threat_score, ['width' => '14.14%']);
    $table->construct_header($lang->honeypot_visitor_type, ['width' => '14.14%']);
    $table->construct_header($lang->honeypot_ip_address, ['width' => '14.14%']);
    $table->construct_header($lang->honeypot_created_at, ['width' => '14.14%']);
    $table->construct_header($lang->honeypot_actions, ['width' => '2%']);

    $query = $db->simple_select("project_honeypot", "*", null, array('order_by' => 'created_at', 'order_dir' => 'DESC', 'limit_start' => $start, 'limit' => $perpage));
    while ($row = $db->fetch_array($query)) {
        $data = [
            'username' => htmlspecialchars_uni($row['username']),
            'email' => htmlspecialchars_uni($row['email']),
            'ip_address' => $row['ip_address'],
            'last_activity' => $row['last_activity']
                . " day" . ($row['last_activity'] != 0 && $row['last_activity'] > 1 ? 's' : '') . " ago",
            'threat_score' => $row['threat_score'],
            'visitor_type' => $row['visitor_type'],
            'created_at' => "<abbr title=\"" . date("jS M Y H:i", $row['created_at']) . "\">"
                . my_date('relative', $row['created_at']) . "</abbr>",
            'url' => 'https://www.projecthoneypot.org/ip_' . $row['ip_address']
        ];

        // Threat score colour code
        $style = '';
        if ($data['threat_score'] >= 50 && $data['threat_score'] < 75) {
            $style = 'color: #fff; background-color: #de9f2a;';
        } elseif ($data['threat_score'] >= 75) {
            $style = 'color: #fff; background-color: #ff5050;';
        }

        $table->construct_cell($data['username']);
        $table->construct_cell($data['email']);
        $table->construct_cell($data['last_activity']);
        $table->construct_cell($data['threat_score'], ['style' => $style]);
        $table->construct_cell($data['visitor_type']);
        $table->construct_cell($data['ip_address']);
        $table->construct_cell($data['created_at']);
        $table->construct_cell("<a href=\"" . $data['url'] . "\" target=\"_blank\"><img src=\"styles/{$page->style}/images/icons/find.png\" title=\"{$lang->honeypot_view}\" alt=\"{$lang->honeypot_view}\" /></a>");
        $table->construct_row();
    }

    if ($table->num_rows() == 0) {
        $table->construct_cell($lang->honeypot_no_logs, array("colspan" => "5"));
        $table->construct_row();
    }

    $table->output($lang->honeypot);

    // Do we need to construct the pagination?
    if ($rescount > $perpage) {
        echo draw_admin_pagination($pagecnt, $perpage, $rescount, "index.php?module=tools-honeypot&amp;perpage=" . $perpage);
    }

    $page->output_footer();
}

**Comment by mustaphaturk** [comment]
Sorry for these codes like spaghetti.
`<?php
// Disallow direct access to this file for security reasons
if (!defined("IN_MYBB")) {
    die("Direct initialization of this file is not allowed.<br /><br />Please make sure IN_MYBB is defined.");
}

$page->add_breadcrumb_item($lang->honeypot, "index.php?module=tools-honeypot");

$sub_tabs['honeypot'] = array(
    'title' => $lang->honeypot,
    'link' => "index.php?module=tools-honeypot",
    'description' => $lang->honeypot_logs_desc
);

if (!$mybb->input['action']) {
    $page->output_header($lang->spam_logs);

    $page->output_nav_tabs($sub_tabs, 'honeypot');

    $perpage = $mybb->get_input('perpage', MyBB::INPUT_INT);
    if (!$perpage) {
        $perpage = 20;
    }

    $query = $db->simple_select("project_honeypot", "COUNT(id) AS count");
    $rescount = $db->fetch_field($query, "count");

    // Figure out if we need to display multiple pages.
    if ($mybb->input['page'] != "last") {
        $pagecnt = $mybb->get_input('page', MyBB::INPUT_INT);
    }

    $logcount = (int)$rescount;
    $pages = $logcount / $perpage;
    $pages = ceil($pages);

    if ($mybb->input['page'] == "last") {
        $pagecnt = $pages;
    }

    if ($pagecnt > $pages) {
        $pagecnt = 1;
    }

    if ($pagecnt) {
        $start = ($pagecnt - 1) * $perpage;
    } else {
        $start = 0;
        $pagecnt = 1;
    }

    $table = new Table;
    $table->construct_header($lang->honeypot_username, ['width' => '14.14%']);
    $table->construct_header($lang->honeypot_email, ['width' => '14.14%']);
    $table->construct_header($lang->honeypot_last_activity, ['width' => '14.14%']);
    $table->construct_header($lang->honeypot_threat_score, ['width' => '14.14%']);
    $table->construct_header($lang->honeypot_visitor_type, ['width' => '14.14%']);
    $table->construct_header($lang->honeypot_ip_address, ['width' => '14.14%']);
    $table->construct_header($lang->honeypot_created_at, ['width' => '14.14%']);
    $table->construct_header($lang->honeypot_actions, ['width' => '2%']);

    $query = $db->simple_select("project_honeypot", "*", null, array('order_by' => 'created_at', 'order_dir' => 'DESC', 'limit_start' => $start, 'limit' => $perpage));
    while ($row = $db->fetch_array($query)) {
        $data = [
            'username' => htmlspecialchars_uni($row['username']),
            'email' => htmlspecialchars_uni($row['email']),
            'ip_address' => $row['ip_address'],
            'last_activity' => $row['last_activity']
                . " day" . ($row['last_activity'] != 0 && $row['last_activity'] > 1 ? 's' : '') . " ago",
            'threat_score' => $row['threat_score'],
            'visitor_type' => $row['visitor_type'],
            'created_at' => "<abbr title=\"" . date("jS M Y H:i", $row['created_at']) . "\">"
                . my_date('relative', $row['created_at']) . "</abbr>",
            'url' => 'https://www.projecthoneypot.org/ip_' . $row['ip_address']
        ];

        // Threat score colour code
        $style = '';
        if ($data['threat_score'] >= 50 && $data['threat_score'] < 75) {
            $style = 'color: #fff; background-color: #de9f2a;';
        } elseif ($data['threat_score'] >= 75) {
            $style = 'color: #fff; background-color: #ff5050;';
        }

        $table->construct_cell($data['username']);
        $table->construct_cell($data['email']);
        $table->construct_cell($data['last_activity']);
        $table->construct_cell($data['threat_score'], ['style' => $style]);
        $table->construct_cell($data['visitor_type']);
        $table->construct_cell($data['ip_address']);
        $table->construct_cell($data['created_at']);
        $table->construct_cell("<a href=\"" . $data['url'] . "\" target=\"_blank\"><img src=\"styles/{$page->style}/images/icons/find.png\" title=\"{$lang->honeypot_view}\" alt=\"{$lang->honeypot_view}\" /></a>");
        $table->construct_row();
    }

    if ($table->num_rows() == 0) {
        $table->construct_cell($lang->honeypot_no_logs, array("colspan" => "5"));
        $table->construct_row();
    }

    $table->output($lang->honeypot);

    // Do we need to construct the pagination?
    if ($rescount > $perpage) {
        echo draw_admin_pagination($pagecnt, $perpage, $rescount, "index.php?module=tools-honeypot&amp;perpage=" . $perpage);
    }

    $page->output_footer();
}
`

**Comment by jamiesage123** [comment]
If the file exists but your web server cannot find it, it sounds like a permission issue on the file itself.

Can you make sure that the file has the correct web user and permission for the web server to access it?

I may be wrong but I don't believe this is an issue with the plugin itself but with your setup, I will double check when I next have access to my personal PC for you.

**Comment by mustaphaturk** [comment]
it has 0644 permission like all other phps

**Comment by mustaphaturk** [comment]
in sitename.com/xxx/index.php

line 766 is this:

`require $modules_dir."/".$run_module."/".$action_file;`
